name       : libglade
version    : 2.6.4
release    : 2
source     :
    - http://ftp.gnome.org/pub/gnome/sources/libglade/2.6/libglade-2.6.4.tar.bz2 : 64361e7647839d36ed8336d992fd210d3e8139882269bed47dc4674980165dec
license    : GPL-2.0
summary    : Glade Programming Library
description: |
    This library allows you to load glade interface files in a program at runtime.
builddeps  :
    - pkgconfig(atk)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(cairo)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
