name       : libglade
version    : 2.6.4
release    : 6
source     :
    - https://download.gnome.org/sources/libglade/2.6/libglade-2.6.4.tar.gz : c41d189b68457976069073e48d6c14c183075d8b1d8077cb6dfb8b7c5097add3
license    : GPL-2.0-only
component  : programming.tools
summary    : Glade Programming Library
description: |
    This library allows you to load glade interface files in a program at runtime.
builddeps  :
    - pkgconfig(atk)
    - pkgconfig(cairo)
    - pkgconfig(gtk+-2.0)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
